### ISSUE TITLE
Add semcov for grpc request and response sizes

### ISSUE THREAD

**Issue by anuragagarwal561994** [open-telemetry/semantic-conventions-java#28]
We are trying to add functionality to yield grpc request and response size metrics.

As I can see it is not part of semcov, how can it be added so we can change the opentelemetry-java instrumentation to yield these metrics?

**Comment by breedx-splk** [comment]
I think this would fall under this: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/rpc/rpc-metrics.md#metric-rpcserverrequestsize

**Comment by anuragagarwal561994** [comment]
Yes this is only the metric we wanted to add as attribute so we can extract that attribute in this metric.

**Comment by breedx-splk** [comment]
Gotcha. I don't think this repo yet has any support for autogenerating the metric conventions from the yaml, so this definitely relates to #12.

**Comment by jack-berg** [comment]
Closing as duplicate of #12. Keeping #12 instead of this because its more generic, and came first.
