### ISSUE TITLE
SemanticAttributes is marked as deprecated, but no instructions on what to use instead

### ISSUE THREAD

**Issue by alexec** [open-telemetry/semantic-conventions-java#47]
Please provide instructions.

**Comment by jkwatson** [comment]
It doesn't look deprecated to me...  https://github.com/open-telemetry/semantic-conventions-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/SemanticAttributes.java#L18

**Comment by alexec** [comment]
There seem to be two version of this library in Maven central with different coordinates. I had the wrong one.

**Comment by jkwatson** [comment]
> There seem to be two version of this library in Maven central with different coordinates. I had the wrong one.

Yes, the old one that was published from the core repository (opentelemetry-java) has indeed been deprecated, and I believe we put the new maven coordinates into the javadoc for that class.
