### ISSUE TITLE
Develop strategy for deprecating / removing experimental semantic conventions

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/semantic-conventions-java#6]
We currently maintain many outdated attributes with `@Deprecated` annotations and previously agreed that this is unsustainable.

For stable semantic conventions, we should obviously retain attributes indefinitely, even if they undergo allowed renames via schema transformation rules.

However, for experimental conventions, we should develop some procedure for end-of-lifing attributes as the conventions churn.

Once we develop this strategy, we should consider removing all current attributes marked as deprecated.

**Comment by breedx-splk** [comment]
I think as long as the prior `@Deprecated` version indicates what the new thing is called or what the user should use instead, then it should be safe to remove these.

Can't the "procedure" to remove these just be a simple as removing them after a release cycle has passed?

**Comment by lmolkova** [comment]
Created generalized issue in the semconv repo - https://github.com/open-telemetry/semantic-conventions/issues/550
Python has the same problem and it's be great to have language-agnostic solution

**Comment by jack-berg** [comment]
This is resolved. See https://github.com/open-telemetry/semantic-conventions-java/issues/50#issuecomment-1998332270 for a full summary of the strategy.
