### ISSUE TITLE
Add "Incubating" to nested class names?

### ISSUE THREAD

**Issue by trask** [open-telemetry/semantic-conventions-java#67]
wdyt of renaming `DbSystemValues` to `DbIncubatingSystemValues` to make usage clearer when importing the nested class directly (and also possibly also since individual enum attribute values can be declared stable / experimental and so it may be more common to need both `DbSystemValues` to `DbIncubatingSystemValues`)

cc @lmolkova @jack-berg

**Comment by jack-berg** [comment]
Seems like a good idea!
