### ISSUE TITLE
Decorate deprecations with suggested replacements

### ISSUE THREAD

**Issue by gabrieljones** [open-telemetry/semantic-conventions-java#69]
Please decorate the deprecations with suggested replacements.
https://github.com/open-telemetry/semantic-conventions-java/pull/62

**Comment by peterdk** [comment]
So yeah, I just started implementing OpenTelemetry, but was getting stuck, cause all the `SemanticAttributes.*` state that they are deprecated, but nowhere indicated what I should use. After some time I figured out that I need `HttpAttributes.*` for my usecase, but nowhere is this indicated, and also not that these classes exist.
