### ISSUE TITLE
Fix possible collisions when attribute is renamed 

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/semantic-conventions-java#72]
See https://github.com/open-telemetry/semantic-conventions/issues/1031 for the details

TL;DR:

`to_const_name` jinja helper generates the same constant name for `foo.bar` and `foo_bar`. 
Tooling will provide a better helper, the workaround for now is to use [custom macro](https://github.com/open-telemetry/opentelemetry-python/pull/3927/files#diff-66cadec87848d09f0256029b0c4ea038c5de01c6abfa98c11c2caa82b0805dff)

e.g. 

```jinja
{%- macro to_const_name_v2(attribute_name) -%}
{{attribute_name | replace("_", "__") | to_const_name}}
{%- endmacro %}
```

So that no collision would happen. 

We're still collecting input on how a good format would look like

**Comment by jack-berg** [comment]
Based on [this comment](https://github.com/open-telemetry/semantic-conventions-java/pull/70#discussion_r1735383083) I believe this is resolved:

> How to resolve client.id vs client_id - https://github.com/open-telemetry/semantic-conventions/issues/1031#issuecomment-2173887975 - manually drop messaging.client_id.
> Existing jinja and build-tools solution implements it already and here's the weaver-based approach in python
> [declare a list of excluded ones](https://github.com/open-telemetry/opentelemetry-python/blob/889f7df41ecca926c7847f3c0913b7b9bbc0dd62/scripts/semconv/templates/registry/weaver.yaml#L7)
[exclude them in jinja](https://github.com/open-telemetry/opentelemetry-python/blob/889f7df41ecca926c7847f3c0913b7b9bbc0dd62/scripts/semconv/templates/registry/semantic_attributes.j2#L22) or in JQ (in python we decided to generate them as comments for transparency)
